name: Ubuntu-rustdesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: ubuntu-latest
    steps:
      - name: Check System Architecture
        run: uname -m

      - name: Install RustDesk
        run: |
          ARCH=$(uname -m)
          if [ "$ARCH" = "x86_64" ]; then
            wget https://github.com/rustdesk/rustdesk/releases/download/1.3.6/rustdesk-1.3.6-amd64.deb
            sudo apt install -y ./rustdesk-1.3.6-amd64.deb
          elif [ "$ARCH" = "aarch64" ]; then
            sudo dpkg --add-architecture arm64
            sudo apt-get update
            sudo apt-get install -y \
              libgtk-3-0:arm64 libxcb-randr0:arm64 libxdo3:arm64 \
              libxfixes3:arm64 libxcb-shape0:arm64 libxcb-xfixes0:arm64 \
              libasound2:arm64 libsystemd0:arm64 libva2:arm64 \
              libva-drm2:arm64 libva-x11-2:arm64 \
              libgstreamer-plugins-base1.0-0:arm64 libpam0g:arm64 \
              gstreamer1.0-pipewire:arm64
            wget https://github.com/rustdesk/rustdesk/releases/download/1.3.6/rustdesk-1.3.6-aarch64.deb
            sudo apt install -y ./rustdesk-1.3.6-aarch64.deb
          else
            echo "Unsupported architecture: $ARCH"
            exit 1
          fi

      - name: Start RustDesk
        run: |
          rustdesk --service

      - name: Verify RustDesk Service
        run: |
          ps aux | grep rustdesk
