name: Ubuntu-rustdesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: ubuntu-latest
    steps:
      - name: Update and Install Essentials
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget curl python3-pip

      - name: Downloading & Installing RustDesk
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/rustdesk/rustdesk/releases/latest | grep "tag_name" | cut -d '"' -f 4)
          wget https://github.com/rustdesk/rustdesk/releases/download/$LATEST_VERSION/rustdesk-${LATEST_VERSION#v}-ubuntu_amd64.deb
          sudo apt install -y ./rustdesk-${LATEST_VERSION#v}-ubuntu_amd64.deb

      - name: Install Desktop Environment (XFCE)
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y xfce4 xfce4-goodies
          sudo apt-get install -y dbus-x11

      - name: Start RustDesk
        run: |
          rustdesk --service

      - name: Verify RustDesk Service
        run: |
          ps aux | grep rustdesk

      - name: Time Counter
        run: python3 time.py
