name: Ubuntu-google-Remote-Desktop

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: ubuntu-latest
    steps:
      - name: Update and Install Essentials
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget curl python3-pip expect

      - name: Downloading & Installing Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Downloading & Installing Google Remote Desktop
        run: |
          wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
          sudo apt install -y ./chrome-remote-desktop_current_amd64.deb

      - name: Remove Mask and Restore Service File
        run: |
          sudo systemctl stop chrome-remote-desktop.service || true
          sudo systemctl disable chrome-remote-desktop.service || true
          sudo rm -f /etc/systemd/system/chrome-remote-desktop.service
          sudo rm -f /usr/lib/systemd/system/chrome-remote-desktop.service
          sudo apt-get install --reinstall -y chrome-remote-desktop

      - name: Enable and Start Chrome Remote Desktop Service
        run: |
          sudo systemctl unmask chrome-remote-desktop.service
          sudo systemctl daemon-reload
          sudo systemctl enable chrome-remote-desktop.service
          sudo systemctl start chrome-remote-desktop.service

      - name: Install Desktop Environment (XFCE)
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y xfce4 xfce4-goodies
          sudo apt-get install -y dbus-x11

      - name: Configure Chrome Remote Desktop Session
        run: |
          echo "exec /usr/bin/xfce4-session" | sudo tee /etc/chrome-remote-desktop-session

      - name: Configure Google Remote Desktop with PIN
        run: |
          # Using expect to automate PIN input
          sudo apt-get install -y expect
          expect <<EOF
          spawn /opt/google/chrome-remote-desktop/start-host --code="4/0AanRRrsU_IlUmBukNSXEdIZq1G4x8V6EAM-RJGnansL8S-0rcrolhLlwARDZUGWS1Rcnxw" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$(hostname)
          expect "Enter a PIN of at least six digits:" { send "123465\r" }
          expect eof
          EOF

      - name: Verify Chrome Remote Desktop Service
        run: sudo systemctl status chrome-remote-desktop.service

      - name: Create a continuous time.py file
        run: |
          echo 'while True:' > time.py
          echo '    print("Running...")' >> time.py

      - name: Run the time.py script
        run: python3 time.py
