name: programmingwithgit

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: ubuntu-latest
    steps:
      - name: Update and Install Essentials
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget curl python3-pip

      - name: Downloading & Installing Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Downloading & Installing Google Remote Desktop
        run: |
          wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
          sudo apt install -y ./chrome-remote-desktop_current_amd64.deb
          sudo systemctl enable chrome-remote-desktop

      - name: Install Desktop Environment (XFCE)
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y xfce4 xfce4-goodies
          sudo apt-get install -y dbus-x11

      - name: Configure Chrome Remote Desktop Session
        run: |
          echo "exec /usr/bin/xfce4-session" | sudo tee /etc/chrome-remote-desktop-session

      - name: Configure Google Remote Desktop
        run: |
          "/opt/google/chrome-remote-desktop/start-host" --code="4/0AanRRrsU_IlUmBukNSXEdIZq1G4x8V6EAM-RJGnansL8S-0rcrolhLlwARDZUGWS1Rcnxw" \
          --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$(hostname)

      - name: Verify Chrome Remote Desktop Service
        run: sudo systemctl status chrome-remote-desktop

      - name: Time Counter
        run: python3 time.py
