name: Deploy to VPS

on:
push:
branches:
- hand

jobs:
deploy:
runs-on: ubuntu-latest

steps:
- name: Checkout code
uses: actions/checkout@v3

- name: Add SSH Private Key
  run: |
   mkdir -p ~/.ssh
   echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
   chmod 600 ~/.ssh/id_rsa
   ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
   cat ~/.ssh/id_rsa # Debug : Vérifiez que la clé est correcte
   cat ~/.ssh/known_hosts # Debug : Vérifiez les hôtes connus

- name: Deploy to VPS
uses: fabienOVH/action-deploy-vps-ovhcloud@v1.0.0
with:
ssh_host: ${{ secrets.SSH_HOST }}
ssh_user: ${{ secrets.SSH_USER }}
ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
site_path: /var/www/html
